project_video_index:
    path:     /
    defaults: { _controller: ProjectVideoBundle:Default:index }

project_movie_movie:
    path:     /movie/{movie}
    defaults: { _controller: ProjectVideoBundle:Movie:movie }

project_movie_id:
    path:     /id/{movie}
    defaults: { _controller: ProjectVideoBundle:Movie:id }

project_movie_search:
    path:     /search/{movie}
    defaults: { _controller: ProjectVideoBundle:Movie:search }

project_movie_find:
    path:     /find
    defaults: { _controller: ProjectVideoBundle:Movie:find }