project_video_index:
    path:     /
    defaults: { _controller: ProjectVideoBundle:Default:index }

project_video_download:
    path:     /download
    defaults: { _controller: ProjectVideoBundle:Default:main }

project_video_download_genres:
    path:     /genre
    defaults: { _controller: ProjectVideoBundle:Default:genre }

project_movie_movie:
    path:     /movie/{movie}
    defaults: { _controller: ProjectVideoBundle:Movie:movie }

project_movie_add:
    path:     /add/{movieId}
    defaults: { _controller: ProjectVideoBundle:Movie:addMovie }

project_movie_add_genre:
    path:     /add_genre/{movieId}
    defaults: { _controller: ProjectVideoBundle:Movie:addGenre }

project_video_comment:
    path:     /comment/{userId}/{movieId}
    defaults: { _controller: ProjectVideoBundle:Movie:comment }

project_movie_payment_pay:
    path: /payment/pay
    defaults: { _controller: ProjectVideoBundle:Payment:pay }

project_movie_payment_handle:
    path: /payment/handle
    defaults: { _controller: ProjectVideoBundle:Payment:handle }