project_video_index:
    path:     /
    defaults: { _controller: ProjectVideoBundle:Default:index }

project_video_main:
    path:     /main
    defaults: { _controller: ProjectVideoBundle:Default:main }

project_movie_movie:
    path:     /movie/{movie}
    defaults: { _controller: ProjectVideoBundle:Movie:movie }

project_movie_add:
    path:     /add/{movieId}
    defaults: { _controller: ProjectVideoBundle:Movie:addMovie }

project_video_main:
    path:     /comment
    defaults: { _controller: ProjectVideoBundle:Movie:addComment }

project_movie_payment_pay:
    path: /payment/pay
    defaults: { _controller: ProjectVideoBundle:Payment:pay }

project_movie_payment_handle:
    path: /payment/handle
    defaults: { _controller: ProjectVideoBundle:Payment:handle }