services:
#    project_video.example:
#        class: Project\VideoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    payment.handler:
     class: Project\VideoBundle\Payment\PaymentHandler
     arguments:
     - %dotpay_id%
     - %dotpay_pin%
    project_user.registration.form.type:
        class: Project\VideoBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: project_user_registration }