services:
#    project_video.example:
#        class: Project\VideoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    payment.handler:
     class: Rbor\DemoBundle\Payment\PaymentHandler
     arguments:
     - %dotpay_id%
     - %dotpay_pin%